node_url_ws: "ws://127.0.0.1:35998"            # Websocket URL for a Zenon node
rocket_chat_url: ""                            # The Rocket Chat server URL
rocket_chat_username: ""                       # Rocket Chat username for the service to use
rocket_chat_password: ""                       # Rocket Chat password for the service to use
rocket_chat_private_channel_name: ""           # The Rocket Chat channel's name used as the private chat